server:
  servlet:
    context-path: /system
  port: 63110
#?????
spring:
  application:
    name: system-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xc_system?serverTimezone=UTC&userUnicode=true&useSSL=false
    username: root
    password: jiaoSDSSKaiai123
  data:
    redis:
      host: 120.46.13.225
      port: 6379
      database: 1
      password: jiaoSDSSKaiai123
# ????????
logging:
  config: classpath:log4j2-dev.xml
# swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v1/api-docs
  packages-to-scan: com.xuecheng.system
mybatis-plus:
  type-aliases-package: com.xuecheng.system.model.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml
